defaults:
  route:
    stage_key: Cast
    demand_qty: 1000
  picks_by_material:
    Nitrogen: Nitrogen Production
    Oxygen: Oxygen Production
    Dolomite: Dolomite Production
    Burnt Lime: Burnt Lime Production

runs:
  - name: regular_as_cast
    picks_by_material:
      Liquid Steel: Regular Steel
      Cast Steel (IP1): Continuous Casting (R)


